# Changes here will be overwritten by Copier
_commit: 1b56b0a
_src_path: gh:avcopan/copier-pixi-python
anaconda_org_name: avcopan
author_email: avcopan@uga.edu
author_name: Andreas V. Copan
github_org_name: avcopan
package_name: picbh
